POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 4549,
  "protocol": "http",
  "stubs": [
    {
      "predicates": [
        { "equals": { "method": "POST", "path": "/api/temperature", "headers": { "Content-Type": "application/json" } } },
        { "contains": { "body": "\"value\"" } }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 201,
            "headers": { "Content-Type": "application/json" },
            "body": { "status": "created", "message": "Medição aceite." }
          }
        }
      ]
    }
  ]
}

###
POST http://localhost:4549/api/temperature
Content-Type: application/json

{ "sensor_id": "s1", "value": 25.6 }

### Teste com valor não numérico
POST http://localhost:4561/api/temperature
Content-Type: application/json

{
    "sensor_id": "s1",
    "value": "teste" 
}