# Define a variável 'host' para o Mountebank
@host = http://localhost:4545

###
# GET /api/alunos -> Lista todos os alunos
GET {{host}}/api/alunos

###
# GET /api/alunos/{id} -> Mostra dados de um aluno específico
GET {{host}}/api/alunos/1

###
# POST /api/alunos -> Adiciona um novo aluno
# (O body aqui é apenas para o teste, o mock simples irá ignorá-lo)
POST {{host}}/api/alunos
Content-Type: application/json

{
    "nome": "Carlos",
    "idade": 24,
    "curso": "Economia"
}

###
# PUT /api/alunos/{id} -> Atualiza dados de um aluno existente
PUT {{host}}/api/alunos/1
Content-Type: application/json

{
    "nome": "Ana Silva (Atualizada)",
    "idade": 23
}

###
# DELETE /api/alunos/{id} -> Remove um aluno
DELETE {{host}}/api/alunos/1